### ISSUE TITLE
HTTP ERROR 500 in my site

### ISSUE THREAD

**Issue by DongHongfei** [discoursehosting/discourse-sitemap#5]
hey, I use this plugin in my site, but after i update yesterday, i can't visit the sitmap page.
here it is: http://ionichina.com/sitemap.xml.

**Comment by wanoo21** [comment]
HI also have this issue!

**Comment by discoursehosting** [comment]
I am sorry, we are unable to reproduce this.
@DongHongfei  can you please provide the Rails logging (stack trace) of the error ?

**Comment by eldyvoon** [comment]
+1, have this issue too.

**Comment by discoursehosting** [comment]
Unless someone provides the Rails logging (stack trace) we're unable to understand what is going on, and we're unable to fix this issue.

**Comment by wanoo21** [comment]
@discoursehosting There're any commands line to do that?

**Comment by wanoo21** [comment]
**Found, maybe that could help you!**

Started GET "/sitemap.xml" for 81.245.52.234 at 2017-10-08 14:09:33 +0000
Processing by DiscourseSitemap::SitemapController#index as XML
  Rendering plugins/discourse-sitemap/app/views/discourse_sitemap/sitemap/index.erb
  Rendered plugins/discourse-sitemap/app/views/discourse_sitemap/sitemap/_header.erb (1.2ms)
  Rendered plugins/discourse-sitemap/app/views/discourse_sitemap/sitemap/index.erb (46.0ms)
Completed 500 Internal Server Error in 149ms (ActiveRecord: 13.8ms)
ActionView::Template::Error (comparison of Fixnum with nil failed)
/var/www/discourse/plugins/discourse-sitemap/app/views/discourse_sitemap/sitemap/index.erb:3:in `>'
Started GET "/sitemap.xml" for 81.245.52.234 at 2017-10-08 14:09:35 +0000
Processing by DiscourseSitemap::SitemapController#index as XML
  Rendering plugins/discourse-sitemap/app/views/discourse_sitemap/sitemap/index.erb
  Rendered plugins/discourse-sitemap/app/views/discourse_sitemap/sitemap/_header.erb (0.8ms)
  Rendered plugins/discourse-sitemap/app/views/discourse_sitemap/sitemap/index.erb (17.3ms)
Completed 500 Internal Server Error in 145ms (ActiveRecord: 104.4ms)
ActionView::Template::Error (comparison of Fixnum with nil failed)
/var/www/discourse/plugins/discourse-sitemap/app/views/discourse_sitemap/sitemap/index.erb:3:in `>'

**Comment by discoursehosting** [comment]
Thank you. Very weird though. 
Can you please tell me what your value of the sitemap_topics_per_page site setting is?

**Comment by wanoo21** [comment]
As they were by default - 10000!
Must change it?

**Comment by wanoo21** [comment]
I did change this number to 1000 but nothing changed!
This issue could be because of adding SSL?
Sometime it's open but after refreshing give HTTP ERROR 500!

**Comment by DongHongfei** [comment]
My sitemap_topics_per_page value is 1000, after I change the number, I can visit the sitemap.xml, but after refreshing give HTTP ERROR 500!

**Comment by eldyvoon** [comment]
@discoursehosting you can't see the error at ur side? try to use the latest version of discourse, few of us already having this issue.

**Comment by discoursehosting** [comment]
Fixed it. In Rails 5 render :text is apparently deprecated.

The error only occurred when serving sitemap from cache, that is why it worked exactly once every time.

**Comment by wanoo21** [comment]
@discoursehosting Thank you very much, after updating works nicely ;)

**Comment by wanoo21** [comment]
@discoursehosting does it support https?
I have installed SSL on server, but in sitemap all links are through http!

**Comment by discoursehosting** [comment]
Enable site setting force_https ...

**Comment by wanoo21** [comment]
@discoursehosting thank you very much!

**Comment by eldyvoon** [comment]
can repoen this issue? doesn't work on non ssl site. Someone replied it's due to Rails 5 issue. This issue is not solved yet.

**Comment by discoursehosting** [comment]
What does "doesn't work" mean? Any errors you're getting?

**Comment by eldyvoon** [comment]
@discoursehosting 500 error. I think it's the same error with @DongHongfei , it worked on the first time then 500 error after I refresh. Btw, I don't use ssl.

**Comment by discoursehosting** [comment]
Are you sure you have updated the plugin? This looks like the former bug. There is no SSL dependency here.

**Comment by eldyvoon** [comment]
update the plugin? I just installed it yesterday, currently the plugin is at version 1.1. Do I have to update after I install it?

**Comment by discoursehosting** [comment]
That depends whether you installed it before or after the fixes. Please update it and retest.

**Comment by eldyvoon** [comment]
I did `rake plugin:update plugin=discourse-sitemap` and `./launcher rebuild app`, it's working now.
